const Config = {
  PREFIX: "f",
  nhay: [
    "Sua di ma",
    "Sao za",
    "Co di ma",
    "Le di ma",
    "Aloo",
    "Cayy cayy",
    "le di em",
    "co de be yeu oi",
    "sua mau di chu",
    "que ia v con di ngu",
    "bị t sút cay như con chó mò :))",
    "huhu mau di ma",
    "bé yêu của pinky lala",
    "cún cưng ngoan lắm",
    "học lỏm anh hay sao cục dàng",
    "bede bonk l (😉",
    "eii bede cay không",
    "hihi win rõ",
    "cay lắm",
    "mau lên đi má ơi ?",
    "mày ngu mà",
    "mày bệnh hoạn hả",
    "sao mày loạn luân",
    "học lỏm è ?",
    "eii ei",
    "full hd lẹ đi em",
    "chill nào",
    "sua le em",
    "top1 mẹ rùi",
    "bede ngu",
    "con di ngua",
    "eii mẹ mày ngu v",
    "mẹ mày có bầu với teo mò",
    "bá lên xíu đi em",
    "huhu htu cay ói",
    "htu thua trân phi rõ kìa",
    "ngu v htu óc",
    "sủa đi",
    "cố lên con",
    "sồn hăng lên em",
    "sao m yếu v ",
    "cố tí nữa",
    "sao kìa chậm à",
    "hăng hái lên tí chứ",
    "tới sáng đi em=))",
    "cố gắng tí con chó dốt=))",
    "k đc à",
    "con chó ngu cố đê",
    "sao m câm kìa",
    "gà j",
    "mày sợ anh à =))",
    "m gà mà",
    "mày ngu rõ mà",
    "đúng mà",
    "cãi à",
    "mày còn gì khác k",
    "học lỏm kìa",
    "cố tí em",
    "mếu à",
    "sao mếu kìa",
    "tao đã cho m mếu đâu",
    "va lẹ đi con dốt",
    "sao kìa",
    "từ bỏ r à",
    "mạnh mẽ tí đi con đĩ",
    "cố lên con chó ngu",
    "=)) cay tao à con đĩ",
    "sợ tao à",
    "sao sợ tao kìa",
    "cay lắm phải kh",
    "ớt rồi kìa em",
    "mày còn chối à",
    "làm tí đê",
    "mới đó đã mệt r kìa",
    "sao gà mà sồn v",
    "sồn như lúc đầu cho tao",
    "sao à",
    "ai cho m nhai",
    "cay lắm r",
    "từ bỏ đi em",
    "mày nghĩ mày làm t cay đc à",
    "có đâu",
    "tao đang hành m mà",
    "bịa à",
    "cay :)))))",
    "cố lên chó dốt",
    "hăng tiếp đi",
    "tới sáng k em",
    "k tới sáng à",
    "chán v",
    "m gà mà",
    "log acc thay phiên à",
    "coi tụi nó dồn ngu kìa",
    "sợ tao à con chó đần",
    "lại win à",
    "lại win r",
    "lũ cặc cay tao lắm🤣🤣",
    "cố lên đê",
    "sao mới 5p đã câm r",
    "yếu đến thế à",
    "sao kìa",
    "khóc kìa",
    "cầu cứu lẹ ei",
    "ai cứu đc m à :))",
    "tao bá mà",
    "sao m gà thế",
    "hăng lẹ cho tao",
    "con chó eiii🤣",
    "ổn k em",
    "kh ổn r à",
    "mày óc à con chó bẻm=))",
    "mẹ mày ngu à",
    "bú cặc cha m k em",
    "thg giả gái :))",
    "coi nó ngu kìa ae",
    "con chó này giả ngu à",
    "m ổn k",
    "mồ côi kìa",
    "sao v sợ r à",
    "cố gắng tí em",
    "cay cú lắm r",
    "đấy đấy bắt đầu",
    "chảy nước đái bò r à em",
    "sao kìa đừng run",
    "mày run à:))",
    "thg dái lở",
    "cay mẹ m lắm",
    "lgbt xuất trận à con đĩ",
    "thg cặc giết cha mắng mẹ",
    "sủa mạnh eii",
    "mày chết r à:))",
    "sao chết kìa",
    "bị t hành nên muốn chết à",
    "con lồn ngu=))",
    "sao kìa",
    "mạnh lên kìa",
    "yếu sinh lý à",
    "sủa đê",
    "cay à",
    "hăng đê",
    "gà kìa ae",
    "akakaa",
    "óc chó kìa",
    "🤣🤣🤣",
    "ổn không🤣🤣",
    "bất ổn à",
    "ơ kìaaa",
    "hăng hái đê",
    "chạy à 🤣🤣",
    "tởn à",
    "kkkk",
    "mày dốt à",
    "cặc ngu",
    "cháy đê",
    "chat hăng lên",
    "cố lên",
    "mồ côi cay",
    "cay à",
    "cn chó ngu",
    "óc cặc kìa",
    "đĩ đú:))",
    "đú kìa",
    "cùn v",
    "r x",
    "hhhhh",
    "kkakak",
    "sao đú",
    "cặc con",
    "ngu kìa",
    "chat mạnh đê",
    "hăng ee",
    "ơ ơ ơ",
    "sủa cháy đê",
    "sủa mạnh eei",
    "mày óc à con",
    "tao cho m chạy à",
    "con đĩ ngu sủa?",
    "mày chạy à con đĩ lồn",
  ],
  spam: [
    "♡ 𝐥𝐞̂𝐧 𝐬𝐢̀ 𝐩𝐡𝐨̂́ 𝐤𝐡𝐨̂𝐧𝐠 𝐜𝐨́ 𝐡𝐨̀𝐚 𝐜𝐡𝐚̆́𝐜 𝐜𝐡𝐨̂𝐦 𝐛𝐮𝐨̂̀𝐧 𝐥𝐚̆́𝐦 𝐤𝐡𝐨̂𝐧𝐠 𝐛𝐢𝐞̂́𝐭 𝐜𝐨́ 𝐝𝐞̂̃ 𝐤𝐢𝐞̂́𝐦 𝐛𝐚̣𝐧 𝐦𝐨̛́𝐢 𝐤𝐡𝐨̂𝐧𝐠 𝐧𝐮̛̃𝐚 𝐡𝐚𝐲 𝐥𝐚̀ 𝐪𝐮𝐚𝐲 𝐥𝐚̣𝐢 𝐜𝐚́𝐢 𝐜𝐡𝐮́𝐧𝐠 𝐬𝐚𝐧𝐡 𝐠𝐢𝐚 𝐭𝐮̛̉ 𝐚̂𝐲 𝐡𝐚𝐳𝐳 ♡\n\n• . 𝐓𝐡𝐡𝐨𝐚 𝐥𝐮𝐯 𝐏𝐢𝐧𝐤𝐲 . •\n\n♡ 𝐥𝐞̂𝐧 𝐬𝐢̀ 𝐩𝐡𝐨̂́ 𝐤𝐡𝐨̂𝐧𝐠 𝐜𝐨́ 𝐡𝐨̀𝐚 𝐜𝐡𝐚̆́𝐜 𝐜𝐡𝐨̂𝐦 𝐛𝐮𝐨̂̀𝐧 𝐥𝐚̆́𝐦 𝐤𝐡𝐨̂𝐧𝐠 𝐛𝐢𝐞̂́𝐭 𝐜𝐨́ 𝐝𝐞̂̃ 𝐤𝐢𝐞̂́𝐦 𝐛𝐚̣𝐧 𝐦𝐨̛́𝐢 𝐤𝐡𝐨̂𝐧𝐠 𝐧𝐮̛̃𝐚 𝐡𝐚𝐲 𝐥𝐚̀ 𝐪𝐮𝐚𝐲 𝐥𝐚̣𝐢 𝐜𝐚́𝐢 𝐜𝐡𝐮́𝐧𝐠 𝐬𝐚𝐧𝐡 𝐠𝐢𝐚 𝐭𝐮̛̉ 𝐚̂𝐲 𝐡𝐚𝐳𝐳 ♡\n\n• . 𝐓𝐡𝐡𝐨𝐚 𝐥𝐮𝐯 𝐏𝐢𝐧𝐤𝐲 . •\n\n♡ 𝐥𝐞̂𝐧 𝐬𝐢̀ 𝐩𝐡𝐨̂́ 𝐤𝐡𝐨̂𝐧𝐠 𝐜𝐨́ 𝐡𝐨̀𝐚 𝐜𝐡𝐚̆́𝐜 𝐜𝐡𝐨̂𝐦 𝐛𝐮𝐨̂̀𝐧 𝐥𝐚̆́𝐦 𝐤𝐡𝐨̂𝐧𝐠 𝐛𝐢𝐞̂́𝐭 𝐜𝐨́ 𝐝𝐞̂̃ 𝐤𝐢𝐞̂́𝐦 𝐛𝐚̣𝐧 𝐦𝐨̛́𝐢 𝐤𝐡𝐨̂𝐧𝐠 𝐧𝐮̛̃𝐚 𝐡𝐚𝐲 𝐥𝐚̀ 𝐪𝐮𝐚𝐲 𝐥𝐚̣𝐢 𝐜𝐚́𝐢 𝐜𝐡𝐮́𝐧𝐠 𝐬𝐚𝐧𝐡 𝐠𝐢𝐚 𝐭𝐮̛̉ 𝐚̂𝐲 𝐡𝐚𝐳𝐳 ♡\n\n• . 𝐓𝐡𝐡𝐨𝐚 𝐥𝐮𝐯 𝐏𝐢𝐧𝐤𝐲 . •\n\n♡ 𝐥𝐞̂𝐧 𝐬𝐢̀ 𝐩𝐡𝐨̂́ 𝐤𝐡𝐨̂𝐧𝐠 𝐜𝐨́ 𝐡𝐨̀𝐚 𝐜𝐡𝐚̆́𝐜 𝐜𝐡𝐨̂𝐦 𝐛𝐮𝐨̂̀𝐧 𝐥𝐚̆́𝐦 𝐤𝐡𝐨̂𝐧𝐠 𝐛𝐢𝐞̂́𝐭 𝐜𝐨́ 𝐝𝐞̂̃ 𝐤𝐢𝐞̂́𝐦 𝐛𝐚̣𝐧 𝐦𝐨̛́𝐢 𝐤𝐡𝐨̂𝐧𝐠 𝐧𝐮̛̃𝐚 𝐡𝐚𝐲 𝐥𝐚̀ 𝐪𝐮𝐚𝐲 𝐥𝐚̣𝐢 𝐜𝐚́𝐢 𝐜𝐡𝐮́𝐧𝐠 𝐬𝐚𝐧𝐡 𝐠𝐢𝐚 𝐭𝐮̛̉ 𝐚̂𝐲 𝐡𝐚𝐳𝐳 ♡\n\n• . 𝐓𝐡𝐡𝐨𝐚 𝐥𝐮𝐯 𝐏𝐢𝐧𝐤𝐲 . •\n\n♡ 𝐥𝐞̂𝐧 𝐬𝐢̀ 𝐩𝐡𝐨̂́ 𝐤𝐡𝐨̂𝐧𝐠 𝐜𝐨́ 𝐡𝐨̀𝐚 𝐜𝐡𝐚̆́𝐜 𝐜𝐡𝐨̂𝐦 𝐛𝐮𝐨̂̀𝐧 𝐥𝐚̆́𝐦 𝐤𝐡𝐨̂𝐧𝐠 𝐛𝐢𝐞̂́𝐭 𝐜𝐨́ 𝐝𝐞̂̃ 𝐤𝐢𝐞̂́𝐦 𝐛𝐚̣𝐧 𝐦𝐨̛́𝐢 𝐤𝐡𝐨̂𝐧𝐠 𝐧𝐮̛̃𝐚 𝐡𝐚𝐲 𝐥𝐚̀ 𝐪𝐮𝐚𝐲 𝐥𝐚̣𝐢 𝐜𝐚́𝐢 𝐜𝐡𝐮́𝐧𝐠 𝐬𝐚𝐧𝐡 𝐠𝐢𝐚 𝐭𝐮̛̉ 𝐚̂𝐲 𝐡𝐚𝐳𝐳 ♡\n\n• . 𝐓𝐡𝐡𝐨𝐚 𝐥𝐮𝐯 𝐏𝐢𝐧𝐤𝐲 . •\n\n",
  ],
  motchu: [
    "eii",
    "sua",
    "di",
    "cay",
    "con",
    "rai",
    "ngu",
    "co",
    "le",
    "mau",
    "len",
    "em",
    "oi",
    "cay",
    "tiếp",
    "đi",
    "eii co di",
    "🤣",
    "óc",
    "hihi",
    "sủa ay lẹ đi",
    "cang",
    "di",
    "cay",
    "a",
    "nhanh",
    "de",
    "cn",
    "ngu",
    "kak",
    "cay",
    "lm",
    "r",
    "t",
    "manh",
    "ma",
    "alo",
    "m",
    "ngu",
    "a",
    "oc",
    "kia",
    "akkaka",
    "cay",
    "alo",
    "suaa",
    "eii",
    "oc",
    "kia",
    "nhay",
    "ei",
    "cay",
    "cu",
    "a",
    "t",
    "ba",
    "v",
    "ak",
    "ui",
    "cay",
    "lam",
    "r",
    "kaka",
    "em",
    "ei",
    "s4a",
    "manh",
    "de",
    "cay",
    "ak",
    "cu",
    "s4ua",
    "ne",
    "di",
    "me",
    "may",
    "kaka",
    "a",
    "em",
    "t",
    "ba",
    "kiki",
    "sao",
    "do",
    "sao",
    "ngu",
    "da",
    "oc",
    "kia",
    "keke",
    "alo",
    "con",
    "ngu",
    "kia",
    "di",
    "me",
    "may",
  ],
  chui: [
    "sủa lẹ đi",
    "úi cn bướm khắm:))))",
    "cn già mày đập đt mày à eyy:))) ",
    "úi coi cn bẻm nó bị chà đạp kìa:)))",
    "khắm chui dô bướm con đĩ già nó chặn keo núp trỏng à:))))",
    "câm à con ngu:)))",
    " eyyy:))",
    "úi cái con hôi:)))",
    "chết cn già mày à:)))",
    "địt con cụ mày phọt khí bướm:)))",
    "úi cha bị úp:))) con trốn đâu r ae:)))",
    "ơi sao m ngu vậy",
    "M là con chó dưới chân t phải k?",
    "êi culi",
    "nào mày mới bằng được cái móng chân tao á",
    "con mẹ mày ngu à",
    "con chó m sủa lẹ t coi",
    "m ngu mà phải không",
    "bede sủa lẹ đi",
    "thằng đầu đinh đâu rồi",
    "sồn lên với tao đi nè thằng boài",
    "thằng như mày xứng đáng ăn cứt tao á",
    "cố gắng mà để win tao nhe",
    "tao bất bại mà thằng ngu",
    "ẳng hăng vào đi chứ mày ẳng gì mà nhạt nhẽo thế",
    "mạnh mẽ lên xem nào",
    "kém cỏi thế thằng mồ côi",
    "phản kháng êi sao đứng yên chịu trận vậy",
    "bất hiếu à",
    "thằng đú m sủa đi nào",
    "mẹ mày bị tao đầu độc tới chết mà",
    "tao trùm mẹ rồi còn gì mà cãi nữa",
    "kiki sủa đi nè",
    "đàn ông hay đàn bà mà yếu đuối vậy",
    "mau đi nè em êi",
    "chậm chạp vậy",
    "thằng bất tài vô dụng sủa mạnh lên đi",
    "bà già mày bị tao treo cổ lên trên trần nhà mà",
    "mày còn gì mới nữa không đó em",
    "thằng đầu đinh cay cú tao à :)))",
    "tao bá đạo vcl 🤣",
    "êi thằng nghèo sao câm rồi",
    "mày xứng đáng ăn cứt tao :))",
    "thằng vô sinh cay cú tao à",
    "mày cố gắng để được như tao đi",
    "bắt chước tao à thằng ngu",
    "quỳ lạy van xin tao đi nè",
    "con hai néo như mày đang diễn hài cho tao cười đấy à",
    "bị tao chửi tới hóa dại luôn rồi à",
    "vô sinh mà đòi đẻ con à thằng boài",
    "con cặc chưa mở mắt mà đòi đụ ai",
    "mày sợ tao rồi hả",
    "khắc tinh đời mày là tao nè",
    "sủa hăng vào cho tao có hứng êi",
    "thằng chó đẻ dân tộc miên hay sao mà đen thế",
    "cố lên đi nè em êi",
    "sắp win được rồi á",
    "có cửa để win tao không",
    "mày đang nằm mơ hay sao á",
    "tao bất bại cmnr",
    "tao là bá chủ thiên hạ đấy",
    "tới sáng không",
    "mày sửa nữa đi sao mà im re rồi",
    "tao cho mày câm chưa mà mày câm thế",
    "đấu tranh đê thằng nhu nhược",
    "hăng hái lên đê em êi",
    "đàn ông mà sức lức như đàn bả vậy",
    "cay cú ôm hận tao suốt đời nè phải không",
    "úi cái con chó này bị ngu à",
  ],
  reo: ["con {name} xì trum 🤣",
" con mập {name} ",
" {name} óc sợ à em 🤣 ",
" {name} ngu sủa liên tục",
" {name} ngu cay",
" con {name} bướm trâu 🤣",
" mẹ con {name} bị tao trap ",
" {name} bónk",
" {name} có mẹ ko em ",
" con {name} chắc ko có mẹ r 🤣 ",
" {name} lồn mồ côi 🤣 ",
" mẹ mày chết r à {name} ",
" con {name} mập  ",
"con {name} cay à em",
"con {name} mồ côi",
"con bónk {name} ",
"nhìn con {name} có vẻ sắp chạy 🤣🙄",
" con lùn lùn {name} ",
"con {name} cay 100% r ae ",
"con {name} xì trum cay",
"con lgbt {name} mồ côi ",
"mồ côi = {name} ",
"sợ à con {name} ",
" {name} dái",
" cay cú à {name} ",
" :))) con {name} ngu ngang con già nó",
" {name} óc bím",
"con boài {name} ",
" {name} bê đê cay ",
" {name} lồn mẹ mày bị tao trap mà ",
" {name} cái lồn ",
" con {name} lag à ",
" nhấn help đê con {name} ",
"con {name} gay à ae ",
"sợ à {name} cặc",
"{name} lgbt cay ",
" {name} cặc",
"{name} boài chết r à:)))",
" con chó {name} sợ tao lắm ",
" {name} lồn cay",
" con già m ăn cứt tao mà {name} 🤣",
" {name} dái",
" úi con {name} bị ae tao thay phiên nhau bash cái đầu 🤣 ",
" {name} óc cay à em",
" {name} lồn ko có mẹ ",
" {name} lồn mẹ rip 💀",
" con {name} lồn thiếu thốn tình thương ",
" {name} bị tao fake mẹ đẻ xong bỏ 🤣🙄",
" {name} lồn cay r ae ",
"con già mày {name} ê",
" mẹ con lồn {name} bị tao oneshot chết r ae 🤣",
" {name} bị ae t đánh ",
" {name} mồ côi ",
" {name} lồn  ",
" {name} bím",
" {name} bónk cay à ",
"úi con bede {name} lùn lùn",
" {name} dái cay 🤣",
" {name} lồn ",
" {name} gay cay ",
"gay à {name}  ",
" {name} boài gay 🤣",
" {name} lồn eo di bi ti 🤣",
" sợ à {name} lồn ",
"con boài {name} cay :))) ",
" con {name} 3 tạ ",
" {name} úi úi",
" {name} lồn bị chửi ",
" {name} lùn cay",
" {name} lùn cay r",
" {name} lùn cay tht r ae 🤣 ",
" con {name} lồn bê đê",
":))) sủa liên tục đee {name} bónk",
" {name} boài minion ",
" :))) con {name} chó ",
"con lồn {name} hay đạp xe đạp ngang nhà tao bị tao chọi đá 🤣",
 " {name} mập ",
" {name} lồn mua thuốc giảm cân uống đi em :))) ",
 " {name} lồn đi lún cả đất ae ạ",
" {name} boài bị cả mxh kì thị 🤣",
 " {name} bướm sợ à ae ",
" con {name} heo quay đâu r ae 🤣",
 " {name} ê ",
" {name} lé  ",
 " {name} lé cay à em",
":))( {name} lé à ",
 " {name} lồn 🤣",
" {name} óc bị ae t log acc thay phiên chửi ",
 " chia ca ra hành con {name} đi ae 💀",
" con {name} bede cay 🤣",
 " {name} bónk  ",
" {name} eo di bi ti ",
 " {name} bónk mồ cô 🤣 ",
"con {name} ngu v ae 🤣"],
    nhayne : [
 "sua de", "cam a", "hang de", "s da", "sợ à m", "toc do ba", " maxspeed em" , "cham da ba", "ph.ế a m", "bia a m", "bot j m", "con ng.u", "cay à ba", "m ph.èn ma", "choi ik m", "dg cau cuu a ba", " wifi miền núi à", "anh bá mà m", "sua de","cn mm","sao ay", "sua de","cay a","maude","nhanh de","sao doa","le de","cay a","sao ddi","sua di m","cay a","djt me m","con mm","hang di iw","sak z o","duoi aak","duoi ke","clm m","cay tak a","speed m","ga ak ccn","nbanh len o","dit me m","sao da","sua de","gay a","yeu ak","met ak","phe kk","nbanh o","ga ak","bede ak","sua de","cay a","nhanh len ow","cham a","sao da","mau di m","sua hang wo","phe ak","sua de","nhanh de ","hang de","mau de","gay a","bede ak","dit mm","cm mm o","dua de","cay vl ak","om han a","sya mau de","nhanh len","nhanh o","sai da","o ke","cjam da","t nhanh vvl","gay o","dua du","toc do de","sua de","cay ak m","sua de m","dy mm","cin me m","phe vat aak","djt ccnm","sua chay di","con cho","ga ak cn","bia a","con cho ngu","soeed di m","dien me r","oc cho","gay aak","con hei","bede ke","oc cac","le de ","dot z ","njanh o ","ngu a ","kskakak ","sao do","ga vcl","sua haf di","djt cmm","m sao","hang de","con cho","nhanh len","phe v ","le o ","clm","so ak","so ke","cay","chay ak","gay ke","clm m","akaka","cn mm","chil di","sua du","nhanh o","ga sk","tk cac","yeu da ","clm","gay a ","non da","con cch","le o ","nhu l","duoi mk","t nhnh vl","m sao","cham ak","moi ak","soa da","con mm","gay ke ","yeu ke","ppheke","ngu ak","sao da","duoi vcl","nbanh di ","kkakak","clm ngu","phe v","ga d","con ngdu","dot ke","phe kke","kkakak","cham fk","yeu ke","lag ak","phe vf","djt vu","ga v","non d","bede mr","phe vat ","nfu da","yeu da","gay a ","con dy","oc cho","phe da","con ngau","non da","win ak","tiep de","moi ak","le de","met ak","phe da","nngu tr","njanh may","toc do","gsy ak","win ak","ngu lon","cmm ay","speed de","djt cu m","sao do","tiep e","mau cai","le len", "m sao ấy em:))", "s/ủa đê $va c/ặc", "sao dị ba:))", ",sợ b/ố à $va :))", "mạnh lên speed mau em:))", "yếu vậy em:)))", "mạnh đi ơ:))", "ra tín hiệu đê $va c/ặc", "m sợ anh à:))) $va b/ướm", "m culi mà $va", "m mạnh lên đi ơ:)))", "m bịa à tk ng.u:))", "m cố đê em:))", "nổi k ba:)))", "mạnh tí đê em rai:)))", "$va cái b.ướm cay:)))", "m hăng lên nào em:)))", "m sao v $va", "k nổi r à:))", "m.ẹ m ng.u à em:))", "m mà $va", "nhây lại anh k ấy $va :)))", "m có trình k ấy:)))", "hay m x.ạo l.ồn hả em:))", "cố đê em", "khuy win à", "tk c.ặc bị anh huy  hw chửi cayyy:)))", "mạnh nuôn em rai:)))", "nhanh de ba", "ph.ế a ba", "dg cau cuu à ba", "ph.èn v ba"
 ],
  time_delay: 2000, // milisecond
};

module.exports = Config;
