const jobData = [
    {
        jobId: 'farmer',
        jobName: 'Nông dân',
        jobEmoji: '🧑‍🌾',
        jobImage: '',
        jobCommand: ['farm', 'harvest', 'thuhoach'],
        jobReturn: '04',
        jobMessages: [
            'Bạn đã thu hoạch được **{reward} {emoji}** nông sản từ trang trại!',
            'Bạn trồng cây táo và đã thu hoạch **{reward} {emoji}** từ cây trồng của mình!',
            'Bạn trồng cây dưa hấu và đã thu hoạch **{reward} {emoji}** từ cây trồng của mình!',
            'Bạn trồng cây cam và đã thu hoạch **{reward} {emoji}** từ cây trồng của mình!',
        ],
        jobDescription: 'Nông dân ',
    },
    {
        jobId: 'carpenter',
        jobName: 'Tiều phu',
        jobEmoji: '👨‍🏭',
        jobImage: '',
        jobCommand: ['chop', 'chatgo'],
        jobReturn: '08',
        jobMessages: [
            'Bạn đi chặt gỗ và đã thu được **{reward} {emoji}** gỗ!',
            'Bạn vào rừng chặt gỗ và đã thu được **{reward} {emoji}** gỗ!',
        ],
        jobDescription: 'Tiều phu',
    },
    {
        jobId: 'miner',
        jobName: 'Thợ mỏ',
        jobEmoji: '👷‍♂️',
        jobImage: '',
        jobCommand: ['mine', 'daoquang'],
        jobReturn: '12',
        jobMessages: [
            'Bạn đã đào được **{reward} {emoji}** kim loại từ đá quặng!',
            'Bạn vào hàng và đã đào được **{reward} {emoji}** quặng!',
        ],
        jobDescription: 'Thợ mỏ',
    },
    {
        jobId: 'hunter',
        jobName: 'Thợ săn',
        jobEmoji: '⚔️',
        jobImage: '',
        jobCommand: ['hunt', 'santhu'],
        jobReturn: '16',
        jobMessages: [
            'Bạn đã đi săn bắn và đã kiếm được **{reward} {emoji}** thịt thú rừng!',
            'Bạn vào dungeon và đã kiếm được **{reward} {emoji}** thịt quái vật!',
        ],
        jobDescription: 'Thợ săn',
    },
    {
        jobId: 'fisherman',
        jobName: 'Ngư dân',
        jobEmoji: '🎣',
        jobImage: '',
        jobCommand: ['fish', 'cauca'],
        jobReturn: '20',
        jobMessages: [
            'Bạn đã đi câu cá và đã bắt được **{reward} {emoji}** cá!',
            'Bạn ra biển và đã bắt được **{reward} {emoji}** cá!',
        ],
        jobDescription: 'Ngư dân ',
    },
];

const itemsData = [
    {
        itemId: '01',
        itemName: 'Liềm Level 1',
        itemDescription: 'Liềm để cày',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '🗡️',
        itemData: {
            type: 'farmer',
            reward: '1-5',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '02',
        itemName: 'Liềm Level 2',
        itemDescription: 'Liềm để cày',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['01'],
        showInShop: true,
        itemEmoji: '🗡️',
        itemData: {
            type: 'farmer',
            reward: '5-15',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '03',
        itemName: 'Liềm Level 3',
        itemDescription: 'Liềm để cày',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['02'],
        showInShop: true,
        itemEmoji: '🗡️',
        itemData: {
            type: 'farmer',
            reward: '15-25',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '04',
        itemName: 'Nông sản',
        itemDescription: 'Nông sản nhận được khi thu hoạch',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '🌾',
        itemData: {
            type: 'default',
            reward: null,
            durability: null,
            content: null,
        },
    },
    {
        itemId: '05',
        itemName: 'Rìu Level 1',
        itemDescription: 'Riu để chặt gỗ',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '🪓',
        itemData: {
            type: 'carpenter',
            reward: '1-5',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '06',
        itemName: 'Rìu Level 2',
        itemDescription: 'Riu để chặt gỗ',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['05'],
        showInShop: true,
        itemEmoji: '🪓',
        itemData: {
            type: 'carpenter',
            reward: '5-15',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '07',
        itemName: 'Rìu Level 3',
        itemDescription: 'Riu để chặt gỗ',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['06'],
        showInShop: true,
        itemEmoji: '🪓',
        itemData: {
            type: 'carpenter',
            reward: '15-25',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '08',
        itemName: 'Gỗ',
        itemDescription: 'Gỗ nhận được khi chặt cây',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '🪵',
        itemData: {
            type: 'default',
            reward: null,
            durability: null,
            content: null,
        },
    },
    {
        itemId: '09',
        itemName: 'Cúp Level 1',
        itemDescription: 'Cúp để đào quặng',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '⛏️',
        itemData: {
            type: 'miner',
            reward: '1-5',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '10',
        itemName: 'Cúp Level 2',
        itemDescription: 'Cúp để đào quặng',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['09'],
        showInShop: true,
        itemEmoji: '⛏️',
        itemData: {
            type: 'miner',
            reward: '5-15',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '11',
        itemName: 'Cúp Level 3',
        itemDescription: 'Cúp để đào quặng',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['10'],
        showInShop: true,
        itemEmoji: '⛏️',
        itemData: {
            type: 'miner',
            reward: '15-25',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '12',
        itemName: 'Quặng',
        itemDescription: 'Bao gồm các loại quặng nhận được khi đào',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '🪨',
        itemData: {
            type: 'default',
            reward: null,
            durability: null,
            content: null,
        },
    },
    {
        itemId: '13',
        itemName: 'Kiếm Level 1',
        itemDescription: 'Kiếm để săn thú rừng',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '⚔️',
        itemData: {
            type: 'hunter',
            reward: '1-5',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '14',
        itemName: 'Kiếm Level 2',
        itemDescription: 'Kiếm để săn thú rừng',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['13'],
        showInShop: true,
        itemEmoji: '⚔️',
        itemData: {
            type: 'hunter',
            reward: '5-15',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '15',
        itemName: 'Kiếm Level 3',
        itemDescription: 'Kiếm để săn thú rừng',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['14'],
        showInShop: true,
        itemEmoji: '⚔️',
        itemData: {
            type: 'hunter',
            reward: '15-25',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '16',
        itemName: 'Thịt quái vật',
        itemDescription: 'Thịt quái vật nhận được khi săn',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '🥩',
        itemData: {
            type: 'default',
            reward: null,
            durability: null,
            content: null,
        },
    },
    {
        itemId: '17',
        itemName: 'Cần câu Level 1',
        itemDescription: 'Cần câu để câu cá',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '🎣',
        itemData: {
            type: 'fisherman',
            reward: '1-5',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '18',
        itemName: 'Cần câu Level 2',
        itemDescription: 'Cần câu để câu cá',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['17'],
        showInShop: true,
        itemEmoji: '🎣',
        itemData: {
            type: 'fisherman',
            reward: '5-15',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '19',
        itemName: 'Cần câu Level 3',
        itemDescription: 'Cần câu để câu cá',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['18'],
        showInShop: true,
        itemEmoji: '🎣',
        itemData: {
            type: 'fisherman',
            reward: '15-25',
            durability: 100,
            content: null,
        },
    },
    {
        itemId: '20',
        itemName: 'Cá',
        itemDescription: 'Cá nhận được khi câu',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '🐟',
        itemData: {
            type: 'default',
            reward: null,
            durability: null,
            content: null,
        },
    },
    {
        itemId: '21',
        itemName: 'Thẻ ngân hàng thường',
        itemDescription: 'Thẻ ngân hàng thường',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: null,
        showInShop: true,
        itemEmoji: '💳',
        itemData: {
            type: 'card',
            interest: 3,
            reward: null,
            durability: null,
            content: null,
        },
    },
    {
        itemId: '22',
        itemName: 'Thẻ ngân hàng VIP level 1',
        itemDescription: 'Thẻ ngân hàng VIP level 1',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['21'],
        showInShop: true,
        itemEmoji: '💳',
        itemData: {
            type: 'card',
            interest: 5,
            reward: null,
            durability: null,
            content: null,
        },
    },
    {
        itemId: '23',
        itemName: 'Thẻ ngân hàng VIP level 2',
        itemDescription: 'Thẻ ngân hàng VIP level 2',
        itemPrice: 100,
        itemStock: 100,
        itemRequires: ['22'],
        showInShop: true,
        itemEmoji: '💳',
        itemData: {
            type: 'card',
            interest: 7,
            reward: null,
            durability: null,
            content: null,
        },
    },
];
anxinMessages = {
    success: [
        'Bạn đã xin được **{money}** từ một người lạ!',
        'Các nhà sư đã cho bạn **{money}**!',
        'Nhà tài trợ BCS đã cho bạn **{money}**!',
        'Công ty BCS cho bạn 1 cái BCS và bạn bán được **{money}**!',
        'Bạn nhặt được **{money}** từ đường phố!',
        'Gura đã thuong cho bạn **{money}**!',
        'Bạn là Đạt Villa và bạn đã xin được **{money}**!',
    ],
    fail: [
        'Bạn xin tiền mà không ai cho!',
        'Bạn làm youtuber, bạn nhận donate mà không ai donate cho bạn!',
        'Bạn là Đạt Villa, nên không ai cho tiền bạn!',
    ],
};
thiefMessages = {
    success: [
        'Bạn đột nhập vào nhà của một người lạ và bạn trộm được *{money}**',
        'Bạn trộm xe của một người lạ và bạn bán được **{money}**!',
        'Bạn đã trộm được một chiếc iPhone và bạn bán được **{money}**!',
    ],
    fail: [
        'Bạn đột nhập vào nhà của một người lạ nhưng không có gì để trộm và bạn đã bị phát hiện, bạn bị bắt vào tù trong **{time}**',
        'Bạn trộm điện thoại của **Dunz** nhưng bạn đã bị phát hiện, bạn bị bắt vào tù trong **{time}**',
        'Bạn trộm xe của **Dunz** nhưng bạn đã bị phát hiện, bạn bị bắt vào tù trong **{time}**',
    ],
};
module.exports = { itemsData, jobData, anxinMessages, thiefMessages };
